#!/usr/bin/with-contenv sh

# Umgebungsvariablen aus options.json lesen
DEVICE_ID=$(jq -r .device_id /data/options.json)
LOCAL_KEY=$(jq -r .local_key /data/options.json)
DEVICE_IP=$(jq -r .device_ip /data/options.json)
MQTT_HOST=$(jq -r .mqtt_host /data/options.json)
MQTT_PORT=$(jq -r .mqtt_port /data/options.json)
MQTT_TOPIC=$(jq -r .mqtt_topic /data/options.json)
MQTT_COMMAND_TOPIC=$(jq -r .mqtt_command_topic /data/options.json)
MQTT_DISCOVERY_PREFIX=$(jq -r .mqtt_discovery_prefix /data/options.json)
MQTT_USER=$(jq -r .mqtt_user /data/options.json)
MQTT_PASSWORD=$(jq -r .mqtt_password /data/options.json)

# Umgebungsvariablen setzen
export DEVICE_ID
export LOCAL_KEY
export DEVICE_IP
export MQTT_HOST
export MQTT_PORT
export MQTT_TOPIC
export MQTT_COMMAND_TOPIC
export MQTT_DISCOVERY_PREFIX
export MQTT_USER
export MQTT_PASSWORD

# Starte das Hauptskript
exec python3 /mqtt_publisher.py
